# Generated by Django 4.2.4 on 2023-09-23 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20210505_1052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinalOrder',
        ),
    ]
